### PR TITLE
Feature/test service

### PR DESCRIPTION
**Pull request by martin-garcia-blanco**
Add tests for the services that call the backend api

### CODE REVIEW

**Review by fdamico — APPROVED** [review]
Very good job @martin-garcia-blanco

**Review by isaporiti — COMMENTED** [review]
By using mirage, we don't need to check google token, right?

**Comment by martin-garcia-blanco** [comment]
> By serving with mirage in our tests, we don't need to check google token when executing `apiCall`, right?

No, With this test, we trust on google library

**Comment by isaporiti** [comment]
> > By serving with mirage in our tests, we don't need to check google token when executing `apiCall`, right?
> 
> No, With this test, we trust on google library

Thanks!

**Pull request merged**
